language: ruby
rvm:
  - 2.0.0
addons:
  postgresql: 9.3
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - psql --version
  - psql -d test -c 'SELECT PostGIS_version();' -U postgres